#!/bin/bash

python3 -m venv media_renamer_service_env
source media_renamer_service_env/bin/activate
pip install watchdog
./rename_media.py -m /mnt/Peliculas/Peliculas/Animadas/ /mnt/Peliculas/Peliculas/Dobladas/
deactivate